-- Module 6: PDF invoice / superbill generation.

-- Invoice number sequence — global, monotonically increasing across years.
-- Format: ECP-YYYY-NNNNNN (the year tracks issuance, not the sequence).
create sequence if not exists invoice_number_seq start 1;

create or replace function next_invoice_number() returns text as $$
  select format(
    'ECP-%s-%s',
    extract(year from now())::int,
    lpad(nextval('invoice_number_seq')::text, 6, '0')
  );
$$ language sql volatile;

-- Storage bucket for invoice PDFs. Private — access only via signed URLs
-- generated by the API after auth/access checks.
insert into storage.buckets (id, name, public)
values ('invoices', 'invoices', false)
on conflict (id) do nothing;

-- Service role uploads/reads. End users only get URLs through the API.
-- Row-level read access is intentionally NOT granted to authenticated users
-- so a leaked URL alone isn't enough — every download flows through our
-- signed-URL handler that verifies the caller can see the trip.

-- Optional: convenience to find an existing invoice by trip id.
create index if not exists invoice_lines_trip_idx
  on invoice_line_items(trip_id);
